# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      # # Cache do DerivedData — evita recompilar tudo do zero
      # - name: Cache DerivedData
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/Library/Developer/Xcode/DerivedData
      #     key: ${{ runner.os }}-deriveddata-${{ hashFiles('**/*.xcodeproj/project.pbxproj') }}
      #     restore-keys: |
      #       ${{ runner.os }}-deriveddata-

      # Build em um único comando
      - name: Build
        run: |
          xcodebuild build \
            -project Challenge17/Challenge17.xcodeproj \
            -scheme "Challenge17 Watch App" \
            -destination 'platform=watchOS Simulator,name=Apple Watch Series 11 (46mm)' \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            -jobs $(sysctl -n hw.logicalcpu) \
            CODE_SIGNING_ALLOWED=NO
